// Generated by gencpp from file custom_sys_msgs/agv_graph.msg
// DO NOT EDIT!


#ifndef CUSTOM_SYS_MSGS_MESSAGE_AGV_GRAPH_H
#define CUSTOM_SYS_MSGS_MESSAGE_AGV_GRAPH_H

#include <ros/service_traits.h>


#include <custom_sys_msgs/agv_graphRequest.h>
#include <custom_sys_msgs/agv_graphResponse.h>


namespace custom_sys_msgs
{

struct agv_graph
{

typedef agv_graphRequest Request;
typedef agv_graphResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct agv_graph
} // namespace custom_sys_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_sys_msgs::agv_graph > {
  static const char* value()
  {
    return "e9c74557c444af09c8ff470ac412ba81";
  }

  static const char* value(const ::custom_sys_msgs::agv_graph&) { return value(); }
};

template<>
struct DataType< ::custom_sys_msgs::agv_graph > {
  static const char* value()
  {
    return "custom_sys_msgs/agv_graph";
  }

  static const char* value(const ::custom_sys_msgs::agv_graph&) { return value(); }
};


// service_traits::MD5Sum< ::custom_sys_msgs::agv_graphRequest> should match 
// service_traits::MD5Sum< ::custom_sys_msgs::agv_graph > 
template<>
struct MD5Sum< ::custom_sys_msgs::agv_graphRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_sys_msgs::agv_graph >::value();
  }
  static const char* value(const ::custom_sys_msgs::agv_graphRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_sys_msgs::agv_graphRequest> should match 
// service_traits::DataType< ::custom_sys_msgs::agv_graph > 
template<>
struct DataType< ::custom_sys_msgs::agv_graphRequest>
{
  static const char* value()
  {
    return DataType< ::custom_sys_msgs::agv_graph >::value();
  }
  static const char* value(const ::custom_sys_msgs::agv_graphRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_sys_msgs::agv_graphResponse> should match 
// service_traits::MD5Sum< ::custom_sys_msgs::agv_graph > 
template<>
struct MD5Sum< ::custom_sys_msgs::agv_graphResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_sys_msgs::agv_graph >::value();
  }
  static const char* value(const ::custom_sys_msgs::agv_graphResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_sys_msgs::agv_graphResponse> should match 
// service_traits::DataType< ::custom_sys_msgs::agv_graph > 
template<>
struct DataType< ::custom_sys_msgs::agv_graphResponse>
{
  static const char* value()
  {
    return DataType< ::custom_sys_msgs::agv_graph >::value();
  }
  static const char* value(const ::custom_sys_msgs::agv_graphResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_SYS_MSGS_MESSAGE_AGV_GRAPH_H
