// Generated by gencpp from file custom_sys_msgs/AgvNodeMsg.msg
// DO NOT EDIT!


#ifndef CUSTOM_SYS_MSGS_MESSAGE_AGVNODEMSG_H
#define CUSTOM_SYS_MSGS_MESSAGE_AGVNODEMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace custom_sys_msgs
{
template <class ContainerAllocator>
struct AgvNodeMsg_
{
  typedef AgvNodeMsg_<ContainerAllocator> Type;

  AgvNodeMsg_()
    : node_id(0)
    , node_name()
    , node_type(0)
    , ref_cnt(0)
    , pos()  {
    }
  AgvNodeMsg_(const ContainerAllocator& _alloc)
    : node_id(0)
    , node_name(_alloc)
    , node_type(0)
    , ref_cnt(0)
    , pos(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _node_id_type;
  _node_id_type node_id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _node_name_type;
  _node_name_type node_name;

   typedef int32_t _node_type_type;
  _node_type_type node_type;

   typedef int32_t _ref_cnt_type;
  _ref_cnt_type ref_cnt;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pos_type;
  _pos_type pos;





  typedef boost::shared_ptr< ::custom_sys_msgs::AgvNodeMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_sys_msgs::AgvNodeMsg_<ContainerAllocator> const> ConstPtr;

}; // struct AgvNodeMsg_

typedef ::custom_sys_msgs::AgvNodeMsg_<std::allocator<void> > AgvNodeMsg;

typedef boost::shared_ptr< ::custom_sys_msgs::AgvNodeMsg > AgvNodeMsgPtr;
typedef boost::shared_ptr< ::custom_sys_msgs::AgvNodeMsg const> AgvNodeMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_sys_msgs::AgvNodeMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_sys_msgs::AgvNodeMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_sys_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'custom_sys_msgs': ['/home/boocax/roswork/src/custom_sys_msgs/msg', '/home/boocax/roswork/devel/share/custom_sys_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_sys_msgs::AgvNodeMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_sys_msgs::AgvNodeMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_sys_msgs::AgvNodeMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_sys_msgs::AgvNodeMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_sys_msgs::AgvNodeMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_sys_msgs::AgvNodeMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_sys_msgs::AgvNodeMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "425f24322817c1acfbde4fee56a7fac2";
  }

  static const char* value(const ::custom_sys_msgs::AgvNodeMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x425f24322817c1acULL;
  static const uint64_t static_value2 = 0xfbde4fee56a7fac2ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_sys_msgs::AgvNodeMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_sys_msgs/AgvNodeMsg";
  }

  static const char* value(const ::custom_sys_msgs::AgvNodeMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_sys_msgs::AgvNodeMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 node_id\n\
string node_name\n\
int32 node_type\n\
int32 ref_cnt\n\
geometry_msgs/Pose pos\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::custom_sys_msgs::AgvNodeMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_sys_msgs::AgvNodeMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.node_id);
      stream.next(m.node_name);
      stream.next(m.node_type);
      stream.next(m.ref_cnt);
      stream.next(m.pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AgvNodeMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_sys_msgs::AgvNodeMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_sys_msgs::AgvNodeMsg_<ContainerAllocator>& v)
  {
    s << indent << "node_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.node_id);
    s << indent << "node_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.node_name);
    s << indent << "node_type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.node_type);
    s << indent << "ref_cnt: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ref_cnt);
    s << indent << "pos: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pos);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_SYS_MSGS_MESSAGE_AGVNODEMSG_H
