// Generated by gencpp from file custom_sys_msgs/AoaTrackingMsg.msg
// DO NOT EDIT!


#ifndef CUSTOM_SYS_MSGS_MESSAGE_AOATRACKINGMSG_H
#define CUSTOM_SYS_MSGS_MESSAGE_AOATRACKINGMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_sys_msgs
{
template <class ContainerAllocator>
struct AoaTrackingMsg_
{
  typedef AoaTrackingMsg_<ContainerAllocator> Type;

  AoaTrackingMsg_()
    : serial_switch(false)
    , task_id(0)
    , task_type(0)
    , vehicle_id(0)
    , remote_control_id(0)  {
    }
  AoaTrackingMsg_(const ContainerAllocator& _alloc)
    : serial_switch(false)
    , task_id(0)
    , task_type(0)
    , vehicle_id(0)
    , remote_control_id(0)  {
  (void)_alloc;
    }



   typedef uint8_t _serial_switch_type;
  _serial_switch_type serial_switch;

   typedef int32_t _task_id_type;
  _task_id_type task_id;

   typedef int32_t _task_type_type;
  _task_type_type task_type;

   typedef int32_t _vehicle_id_type;
  _vehicle_id_type vehicle_id;

   typedef uint16_t _remote_control_id_type;
  _remote_control_id_type remote_control_id;





  typedef boost::shared_ptr< ::custom_sys_msgs::AoaTrackingMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_sys_msgs::AoaTrackingMsg_<ContainerAllocator> const> ConstPtr;

}; // struct AoaTrackingMsg_

typedef ::custom_sys_msgs::AoaTrackingMsg_<std::allocator<void> > AoaTrackingMsg;

typedef boost::shared_ptr< ::custom_sys_msgs::AoaTrackingMsg > AoaTrackingMsgPtr;
typedef boost::shared_ptr< ::custom_sys_msgs::AoaTrackingMsg const> AoaTrackingMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_sys_msgs::AoaTrackingMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_sys_msgs::AoaTrackingMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_sys_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'custom_sys_msgs': ['/home/boocax/roswork/src/custom_sys_msgs/msg', '/home/boocax/roswork/devel/share/custom_sys_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_sys_msgs::AoaTrackingMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_sys_msgs::AoaTrackingMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_sys_msgs::AoaTrackingMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_sys_msgs::AoaTrackingMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_sys_msgs::AoaTrackingMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_sys_msgs::AoaTrackingMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_sys_msgs::AoaTrackingMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8382739c3a150bd5ebcf30730920d2e8";
  }

  static const char* value(const ::custom_sys_msgs::AoaTrackingMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8382739c3a150bd5ULL;
  static const uint64_t static_value2 = 0xebcf30730920d2e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_sys_msgs::AoaTrackingMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_sys_msgs/AoaTrackingMsg";
  }

  static const char* value(const ::custom_sys_msgs::AoaTrackingMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_sys_msgs::AoaTrackingMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool serial_switch\n\
int32 task_id\n\
int32 task_type\n\
int32 vehicle_id\n\
uint16 remote_control_id\n\
";
  }

  static const char* value(const ::custom_sys_msgs::AoaTrackingMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_sys_msgs::AoaTrackingMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.serial_switch);
      stream.next(m.task_id);
      stream.next(m.task_type);
      stream.next(m.vehicle_id);
      stream.next(m.remote_control_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AoaTrackingMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_sys_msgs::AoaTrackingMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_sys_msgs::AoaTrackingMsg_<ContainerAllocator>& v)
  {
    s << indent << "serial_switch: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.serial_switch);
    s << indent << "task_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.task_id);
    s << indent << "task_type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.task_type);
    s << indent << "vehicle_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.vehicle_id);
    s << indent << "remote_control_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.remote_control_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_SYS_MSGS_MESSAGE_AOATRACKINGMSG_H
