// Generated by gencpp from file custom_sys_msgs/boocax_version.msg
// DO NOT EDIT!


#ifndef CUSTOM_SYS_MSGS_MESSAGE_BOOCAX_VERSION_H
#define CUSTOM_SYS_MSGS_MESSAGE_BOOCAX_VERSION_H

#include <ros/service_traits.h>


#include <custom_sys_msgs/boocax_versionRequest.h>
#include <custom_sys_msgs/boocax_versionResponse.h>


namespace custom_sys_msgs
{

struct boocax_version
{

typedef boocax_versionRequest Request;
typedef boocax_versionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct boocax_version
} // namespace custom_sys_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_sys_msgs::boocax_version > {
  static const char* value()
  {
    return "4e95cccfdf0b9419ff2f6d45e4903934";
  }

  static const char* value(const ::custom_sys_msgs::boocax_version&) { return value(); }
};

template<>
struct DataType< ::custom_sys_msgs::boocax_version > {
  static const char* value()
  {
    return "custom_sys_msgs/boocax_version";
  }

  static const char* value(const ::custom_sys_msgs::boocax_version&) { return value(); }
};


// service_traits::MD5Sum< ::custom_sys_msgs::boocax_versionRequest> should match 
// service_traits::MD5Sum< ::custom_sys_msgs::boocax_version > 
template<>
struct MD5Sum< ::custom_sys_msgs::boocax_versionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_sys_msgs::boocax_version >::value();
  }
  static const char* value(const ::custom_sys_msgs::boocax_versionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_sys_msgs::boocax_versionRequest> should match 
// service_traits::DataType< ::custom_sys_msgs::boocax_version > 
template<>
struct DataType< ::custom_sys_msgs::boocax_versionRequest>
{
  static const char* value()
  {
    return DataType< ::custom_sys_msgs::boocax_version >::value();
  }
  static const char* value(const ::custom_sys_msgs::boocax_versionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_sys_msgs::boocax_versionResponse> should match 
// service_traits::MD5Sum< ::custom_sys_msgs::boocax_version > 
template<>
struct MD5Sum< ::custom_sys_msgs::boocax_versionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_sys_msgs::boocax_version >::value();
  }
  static const char* value(const ::custom_sys_msgs::boocax_versionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_sys_msgs::boocax_versionResponse> should match 
// service_traits::DataType< ::custom_sys_msgs::boocax_version > 
template<>
struct DataType< ::custom_sys_msgs::boocax_versionResponse>
{
  static const char* value()
  {
    return DataType< ::custom_sys_msgs::boocax_version >::value();
  }
  static const char* value(const ::custom_sys_msgs::boocax_versionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_SYS_MSGS_MESSAGE_BOOCAX_VERSION_H
