// Generated by gencpp from file custom_sys_msgs/FreeNavAction.msg
// DO NOT EDIT!


#ifndef CUSTOM_SYS_MSGS_MESSAGE_FREENAVACTION_H
#define CUSTOM_SYS_MSGS_MESSAGE_FREENAVACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <custom_sys_msgs/FreeNavActionGoal.h>
#include <custom_sys_msgs/FreeNavActionResult.h>
#include <custom_sys_msgs/FreeNavActionFeedback.h>

namespace custom_sys_msgs
{
template <class ContainerAllocator>
struct FreeNavAction_
{
  typedef FreeNavAction_<ContainerAllocator> Type;

  FreeNavAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  FreeNavAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::custom_sys_msgs::FreeNavActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::custom_sys_msgs::FreeNavActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::custom_sys_msgs::FreeNavActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::custom_sys_msgs::FreeNavAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_sys_msgs::FreeNavAction_<ContainerAllocator> const> ConstPtr;

}; // struct FreeNavAction_

typedef ::custom_sys_msgs::FreeNavAction_<std::allocator<void> > FreeNavAction;

typedef boost::shared_ptr< ::custom_sys_msgs::FreeNavAction > FreeNavActionPtr;
typedef boost::shared_ptr< ::custom_sys_msgs::FreeNavAction const> FreeNavActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_sys_msgs::FreeNavAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_sys_msgs::FreeNavAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_sys_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'custom_sys_msgs': ['/home/boocax/roswork/src/custom_sys_msgs/msg', '/home/boocax/roswork/devel/share/custom_sys_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_sys_msgs::FreeNavAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_sys_msgs::FreeNavAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_sys_msgs::FreeNavAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_sys_msgs::FreeNavAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_sys_msgs::FreeNavAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_sys_msgs::FreeNavAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_sys_msgs::FreeNavAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6aeb3916f316222614ed09e3e8ebd21c";
  }

  static const char* value(const ::custom_sys_msgs::FreeNavAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6aeb3916f3162226ULL;
  static const uint64_t static_value2 = 0x14ed09e3e8ebd21cULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_sys_msgs::FreeNavAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_sys_msgs/FreeNavAction";
  }

  static const char* value(const ::custom_sys_msgs::FreeNavAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_sys_msgs::FreeNavAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
FreeNavActionGoal action_goal\n\
FreeNavActionResult action_result\n\
FreeNavActionFeedback action_feedback\n\
\n\
================================================================================\n\
MSG: custom_sys_msgs/FreeNavActionGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
FreeNavGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: custom_sys_msgs/FreeNavGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# goal: a path to exe\n\
custom_sys_msgs/FreeNav path\n\
\n\
================================================================================\n\
MSG: custom_sys_msgs/FreeNav\n\
geometry_msgs/PoseStamped target_pose\n\
custom_sys_msgs/AgvTrajectoryMsg2 target_path\n\
int32 type\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: custom_sys_msgs/AgvTrajectoryMsg2\n\
int32 task_id\n\
int32 task_type\n\
int32 vehicle_id\n\
int32 free_nav\n\
float64 deadline\n\
geometry_msgs/Pose dst_pose\n\
custom_sys_msgs/AgvLineMsg2[] agv_trajectory\n\
int32 test\n\
================================================================================\n\
MSG: custom_sys_msgs/AgvLineMsg2\n\
int32 segment_id\n\
int32 segment_type\n\
int32 attitude\n\
int32 tracking_mode\n\
float64 speed\n\
float64 precision\n\
float64 arrival_time\n\
float64 departure_time\n\
float64 redundancy_time\n\
geometry_msgs/Pose p_start\n\
geometry_msgs/Pose p_middle\n\
geometry_msgs/Pose p_end\n\
int32 start_node_id\n\
int32 end_node_id\n\
bool crossing\n\
\n\
================================================================================\n\
MSG: custom_sys_msgs/FreeNavActionResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
FreeNavResult result\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalStatus\n\
GoalID goal_id\n\
uint8 status\n\
uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n\
uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n\
uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n\
                            #   and has since completed its execution (Terminal State)\n\
uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n\
uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n\
                            #    to some failure (Terminal State)\n\
uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n\
                            #    because the goal was unattainable or invalid (Terminal State)\n\
uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n\
                            #    and has not yet completed execution\n\
uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n\
                            #    but the action server has not yet confirmed that the goal is canceled\n\
uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n\
                            #    and was successfully cancelled (Terminal State)\n\
uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n\
                            #    sent over the wire by an action server\n\
\n\
#Allow for the user to associate a string with GoalStatus for debugging\n\
string text\n\
\n\
\n\
================================================================================\n\
MSG: custom_sys_msgs/FreeNavResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# no result currently\n\
\n\
================================================================================\n\
MSG: custom_sys_msgs/FreeNavActionFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
FreeNavFeedback feedback\n\
\n\
================================================================================\n\
MSG: custom_sys_msgs/FreeNavFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
geometry_msgs/PoseStamped base_position\n\
";
  }

  static const char* value(const ::custom_sys_msgs::FreeNavAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_sys_msgs::FreeNavAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FreeNavAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_sys_msgs::FreeNavAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_sys_msgs::FreeNavAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::custom_sys_msgs::FreeNavActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::custom_sys_msgs::FreeNavActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::custom_sys_msgs::FreeNavActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_SYS_MSGS_MESSAGE_FREENAVACTION_H
