// Generated by gencpp from file custom_sys_msgs/FreeNavActionGoal.msg
// DO NOT EDIT!


#ifndef CUSTOM_SYS_MSGS_MESSAGE_FREENAVACTIONGOAL_H
#define CUSTOM_SYS_MSGS_MESSAGE_FREENAVACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <custom_sys_msgs/FreeNavGoal.h>

namespace custom_sys_msgs
{
template <class ContainerAllocator>
struct FreeNavActionGoal_
{
  typedef FreeNavActionGoal_<ContainerAllocator> Type;

  FreeNavActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  FreeNavActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::custom_sys_msgs::FreeNavGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::custom_sys_msgs::FreeNavActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_sys_msgs::FreeNavActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct FreeNavActionGoal_

typedef ::custom_sys_msgs::FreeNavActionGoal_<std::allocator<void> > FreeNavActionGoal;

typedef boost::shared_ptr< ::custom_sys_msgs::FreeNavActionGoal > FreeNavActionGoalPtr;
typedef boost::shared_ptr< ::custom_sys_msgs::FreeNavActionGoal const> FreeNavActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_sys_msgs::FreeNavActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_sys_msgs::FreeNavActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_sys_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'custom_sys_msgs': ['/home/boocax/roswork/src/custom_sys_msgs/msg', '/home/boocax/roswork/devel/share/custom_sys_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_sys_msgs::FreeNavActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_sys_msgs::FreeNavActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_sys_msgs::FreeNavActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_sys_msgs::FreeNavActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_sys_msgs::FreeNavActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_sys_msgs::FreeNavActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_sys_msgs::FreeNavActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1220666c97d137b6d10afbf8ccfdcb6b";
  }

  static const char* value(const ::custom_sys_msgs::FreeNavActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1220666c97d137b6ULL;
  static const uint64_t static_value2 = 0xd10afbf8ccfdcb6bULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_sys_msgs::FreeNavActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_sys_msgs/FreeNavActionGoal";
  }

  static const char* value(const ::custom_sys_msgs::FreeNavActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_sys_msgs::FreeNavActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
FreeNavGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: custom_sys_msgs/FreeNavGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# goal: a path to exe\n\
custom_sys_msgs/FreeNav path\n\
\n\
================================================================================\n\
MSG: custom_sys_msgs/FreeNav\n\
geometry_msgs/PoseStamped target_pose\n\
custom_sys_msgs/AgvTrajectoryMsg2 target_path\n\
int32 type\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: custom_sys_msgs/AgvTrajectoryMsg2\n\
int32 task_id\n\
int32 task_type\n\
int32 vehicle_id\n\
int32 free_nav\n\
float64 deadline\n\
geometry_msgs/Pose dst_pose\n\
custom_sys_msgs/AgvLineMsg2[] agv_trajectory\n\
int32 test\n\
================================================================================\n\
MSG: custom_sys_msgs/AgvLineMsg2\n\
int32 segment_id\n\
int32 segment_type\n\
int32 attitude\n\
int32 tracking_mode\n\
float64 speed\n\
float64 precision\n\
float64 arrival_time\n\
float64 departure_time\n\
float64 redundancy_time\n\
geometry_msgs/Pose p_start\n\
geometry_msgs/Pose p_middle\n\
geometry_msgs/Pose p_end\n\
int32 start_node_id\n\
int32 end_node_id\n\
bool crossing\n\
";
  }

  static const char* value(const ::custom_sys_msgs::FreeNavActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_sys_msgs::FreeNavActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FreeNavActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_sys_msgs::FreeNavActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_sys_msgs::FreeNavActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::custom_sys_msgs::FreeNavGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_SYS_MSGS_MESSAGE_FREENAVACTIONGOAL_H
