// Generated by gencpp from file custom_sys_msgs/read_rfidRequest.msg
// DO NOT EDIT!


#ifndef CUSTOM_SYS_MSGS_MESSAGE_READ_RFIDREQUEST_H
#define CUSTOM_SYS_MSGS_MESSAGE_READ_RFIDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_sys_msgs
{
template <class ContainerAllocator>
struct read_rfidRequest_
{
  typedef read_rfidRequest_<ContainerAllocator> Type;

  read_rfidRequest_()
    : rfid()  {
    }
  read_rfidRequest_(const ContainerAllocator& _alloc)
    : rfid(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _rfid_type;
  _rfid_type rfid;





  typedef boost::shared_ptr< ::custom_sys_msgs::read_rfidRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_sys_msgs::read_rfidRequest_<ContainerAllocator> const> ConstPtr;

}; // struct read_rfidRequest_

typedef ::custom_sys_msgs::read_rfidRequest_<std::allocator<void> > read_rfidRequest;

typedef boost::shared_ptr< ::custom_sys_msgs::read_rfidRequest > read_rfidRequestPtr;
typedef boost::shared_ptr< ::custom_sys_msgs::read_rfidRequest const> read_rfidRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_sys_msgs::read_rfidRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_sys_msgs::read_rfidRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_sys_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'custom_sys_msgs': ['/home/boocax/roswork/src/custom_sys_msgs/msg', '/home/boocax/roswork/devel/share/custom_sys_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_sys_msgs::read_rfidRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_sys_msgs::read_rfidRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_sys_msgs::read_rfidRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_sys_msgs::read_rfidRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_sys_msgs::read_rfidRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_sys_msgs::read_rfidRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_sys_msgs::read_rfidRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71937ebb5398ecec907c34ee711d1a8b";
  }

  static const char* value(const ::custom_sys_msgs::read_rfidRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71937ebb5398ececULL;
  static const uint64_t static_value2 = 0x907c34ee711d1a8bULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_sys_msgs::read_rfidRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_sys_msgs/read_rfidRequest";
  }

  static const char* value(const ::custom_sys_msgs::read_rfidRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_sys_msgs::read_rfidRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] rfid\n\
";
  }

  static const char* value(const ::custom_sys_msgs::read_rfidRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_sys_msgs::read_rfidRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rfid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct read_rfidRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_sys_msgs::read_rfidRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_sys_msgs::read_rfidRequest_<ContainerAllocator>& v)
  {
    s << indent << "rfid[]" << std::endl;
    for (size_t i = 0; i < v.rfid.size(); ++i)
    {
      s << indent << "  rfid[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.rfid[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_SYS_MSGS_MESSAGE_READ_RFIDREQUEST_H
