// Generated by gencpp from file custom_sys_msgs/read_rfid.msg
// DO NOT EDIT!


#ifndef CUSTOM_SYS_MSGS_MESSAGE_READ_RFID_H
#define CUSTOM_SYS_MSGS_MESSAGE_READ_RFID_H

#include <ros/service_traits.h>


#include <custom_sys_msgs/read_rfidRequest.h>
#include <custom_sys_msgs/read_rfidResponse.h>


namespace custom_sys_msgs
{

struct read_rfid
{

typedef read_rfidRequest Request;
typedef read_rfidResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct read_rfid
} // namespace custom_sys_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_sys_msgs::read_rfid > {
  static const char* value()
  {
    return "18de2e0b7d7ef6caf5f88adb50d8ab40";
  }

  static const char* value(const ::custom_sys_msgs::read_rfid&) { return value(); }
};

template<>
struct DataType< ::custom_sys_msgs::read_rfid > {
  static const char* value()
  {
    return "custom_sys_msgs/read_rfid";
  }

  static const char* value(const ::custom_sys_msgs::read_rfid&) { return value(); }
};


// service_traits::MD5Sum< ::custom_sys_msgs::read_rfidRequest> should match 
// service_traits::MD5Sum< ::custom_sys_msgs::read_rfid > 
template<>
struct MD5Sum< ::custom_sys_msgs::read_rfidRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_sys_msgs::read_rfid >::value();
  }
  static const char* value(const ::custom_sys_msgs::read_rfidRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_sys_msgs::read_rfidRequest> should match 
// service_traits::DataType< ::custom_sys_msgs::read_rfid > 
template<>
struct DataType< ::custom_sys_msgs::read_rfidRequest>
{
  static const char* value()
  {
    return DataType< ::custom_sys_msgs::read_rfid >::value();
  }
  static const char* value(const ::custom_sys_msgs::read_rfidRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_sys_msgs::read_rfidResponse> should match 
// service_traits::MD5Sum< ::custom_sys_msgs::read_rfid > 
template<>
struct MD5Sum< ::custom_sys_msgs::read_rfidResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_sys_msgs::read_rfid >::value();
  }
  static const char* value(const ::custom_sys_msgs::read_rfidResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_sys_msgs::read_rfidResponse> should match 
// service_traits::DataType< ::custom_sys_msgs::read_rfid > 
template<>
struct DataType< ::custom_sys_msgs::read_rfidResponse>
{
  static const char* value()
  {
    return DataType< ::custom_sys_msgs::read_rfid >::value();
  }
  static const char* value(const ::custom_sys_msgs::read_rfidResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_SYS_MSGS_MESSAGE_READ_RFID_H
