// Generated by gencpp from file custom_sys_msgs/RobotBasicInfoMsg.msg
// DO NOT EDIT!


#ifndef CUSTOM_SYS_MSGS_MESSAGE_ROBOTBASICINFOMSG_H
#define CUSTOM_SYS_MSGS_MESSAGE_ROBOTBASICINFOMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_sys_msgs
{
template <class ContainerAllocator>
struct RobotBasicInfoMsg_
{
  typedef RobotBasicInfoMsg_<ContainerAllocator> Type;

  RobotBasicInfoMsg_()
    : robot_name()
    , robot_ip()
    , robot_mac()
    , if_name()
    , robot_id(0)  {
    }
  RobotBasicInfoMsg_(const ContainerAllocator& _alloc)
    : robot_name(_alloc)
    , robot_ip(_alloc)
    , robot_mac(_alloc)
    , if_name(_alloc)
    , robot_id(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robot_name_type;
  _robot_name_type robot_name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robot_ip_type;
  _robot_ip_type robot_ip;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robot_mac_type;
  _robot_mac_type robot_mac;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _if_name_type;
  _if_name_type if_name;

   typedef int32_t _robot_id_type;
  _robot_id_type robot_id;





  typedef boost::shared_ptr< ::custom_sys_msgs::RobotBasicInfoMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_sys_msgs::RobotBasicInfoMsg_<ContainerAllocator> const> ConstPtr;

}; // struct RobotBasicInfoMsg_

typedef ::custom_sys_msgs::RobotBasicInfoMsg_<std::allocator<void> > RobotBasicInfoMsg;

typedef boost::shared_ptr< ::custom_sys_msgs::RobotBasicInfoMsg > RobotBasicInfoMsgPtr;
typedef boost::shared_ptr< ::custom_sys_msgs::RobotBasicInfoMsg const> RobotBasicInfoMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_sys_msgs::RobotBasicInfoMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_sys_msgs::RobotBasicInfoMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_sys_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'custom_sys_msgs': ['/home/boocax/roswork/src/custom_sys_msgs/msg', '/home/boocax/roswork/devel/share/custom_sys_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_sys_msgs::RobotBasicInfoMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_sys_msgs::RobotBasicInfoMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_sys_msgs::RobotBasicInfoMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_sys_msgs::RobotBasicInfoMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_sys_msgs::RobotBasicInfoMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_sys_msgs::RobotBasicInfoMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_sys_msgs::RobotBasicInfoMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a20f282b03acc33dd1a5d6098520f933";
  }

  static const char* value(const ::custom_sys_msgs::RobotBasicInfoMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa20f282b03acc33dULL;
  static const uint64_t static_value2 = 0xd1a5d6098520f933ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_sys_msgs::RobotBasicInfoMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_sys_msgs/RobotBasicInfoMsg";
  }

  static const char* value(const ::custom_sys_msgs::RobotBasicInfoMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_sys_msgs::RobotBasicInfoMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string robot_name\n\
string robot_ip\n\
string robot_mac\n\
string if_name\n\
int32 robot_id\n\
";
  }

  static const char* value(const ::custom_sys_msgs::RobotBasicInfoMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_sys_msgs::RobotBasicInfoMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_name);
      stream.next(m.robot_ip);
      stream.next(m.robot_mac);
      stream.next(m.if_name);
      stream.next(m.robot_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotBasicInfoMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_sys_msgs::RobotBasicInfoMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_sys_msgs::RobotBasicInfoMsg_<ContainerAllocator>& v)
  {
    s << indent << "robot_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robot_name);
    s << indent << "robot_ip: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robot_ip);
    s << indent << "robot_mac: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robot_mac);
    s << indent << "if_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.if_name);
    s << indent << "robot_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.robot_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_SYS_MSGS_MESSAGE_ROBOTBASICINFOMSG_H
