// Generated by gencpp from file custom_sys_msgs/TrackPathGoal.msg
// DO NOT EDIT!


#ifndef CUSTOM_SYS_MSGS_MESSAGE_TRACKPATHGOAL_H
#define CUSTOM_SYS_MSGS_MESSAGE_TRACKPATHGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <custom_sys_msgs/AgvTrajectoryMsg2.h>

namespace custom_sys_msgs
{
template <class ContainerAllocator>
struct TrackPathGoal_
{
  typedef TrackPathGoal_<ContainerAllocator> Type;

  TrackPathGoal_()
    : path()  {
    }
  TrackPathGoal_(const ContainerAllocator& _alloc)
    : path(_alloc)  {
  (void)_alloc;
    }



   typedef  ::custom_sys_msgs::AgvTrajectoryMsg2_<ContainerAllocator>  _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::custom_sys_msgs::TrackPathGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_sys_msgs::TrackPathGoal_<ContainerAllocator> const> ConstPtr;

}; // struct TrackPathGoal_

typedef ::custom_sys_msgs::TrackPathGoal_<std::allocator<void> > TrackPathGoal;

typedef boost::shared_ptr< ::custom_sys_msgs::TrackPathGoal > TrackPathGoalPtr;
typedef boost::shared_ptr< ::custom_sys_msgs::TrackPathGoal const> TrackPathGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_sys_msgs::TrackPathGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_sys_msgs::TrackPathGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_sys_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'custom_sys_msgs': ['/home/boocax/roswork/src/custom_sys_msgs/msg', '/home/boocax/roswork/devel/share/custom_sys_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_sys_msgs::TrackPathGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_sys_msgs::TrackPathGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_sys_msgs::TrackPathGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_sys_msgs::TrackPathGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_sys_msgs::TrackPathGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_sys_msgs::TrackPathGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_sys_msgs::TrackPathGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "41dbbfcb0dbb3f1d634a3fc79ec5237d";
  }

  static const char* value(const ::custom_sys_msgs::TrackPathGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x41dbbfcb0dbb3f1dULL;
  static const uint64_t static_value2 = 0x634a3fc79ec5237dULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_sys_msgs::TrackPathGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_sys_msgs/TrackPathGoal";
  }

  static const char* value(const ::custom_sys_msgs::TrackPathGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_sys_msgs::TrackPathGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# goal: a path to exe\n\
custom_sys_msgs/AgvTrajectoryMsg2 path\n\
\n\
================================================================================\n\
MSG: custom_sys_msgs/AgvTrajectoryMsg2\n\
int32 task_id\n\
int32 task_type\n\
int32 vehicle_id\n\
int32 free_nav\n\
float64 deadline\n\
geometry_msgs/Pose dst_pose\n\
custom_sys_msgs/AgvLineMsg2[] agv_trajectory\n\
int32 test\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: custom_sys_msgs/AgvLineMsg2\n\
int32 segment_id\n\
int32 segment_type\n\
int32 attitude\n\
int32 tracking_mode\n\
float64 speed\n\
float64 precision\n\
float64 arrival_time\n\
float64 departure_time\n\
float64 redundancy_time\n\
geometry_msgs/Pose p_start\n\
geometry_msgs/Pose p_middle\n\
geometry_msgs/Pose p_end\n\
int32 start_node_id\n\
int32 end_node_id\n\
bool crossing\n\
";
  }

  static const char* value(const ::custom_sys_msgs::TrackPathGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_sys_msgs::TrackPathGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackPathGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_sys_msgs::TrackPathGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_sys_msgs::TrackPathGoal_<ContainerAllocator>& v)
  {
    s << indent << "path: ";
    s << std::endl;
    Printer< ::custom_sys_msgs::AgvTrajectoryMsg2_<ContainerAllocator> >::stream(s, indent + "  ", v.path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_SYS_MSGS_MESSAGE_TRACKPATHGOAL_H
