# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from teb_local_planner/AgvTrajectoryMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import teb_local_planner.msg
import geometry_msgs.msg
import std_msgs.msg

class AgvTrajectoryMsg(genpy.Message):
  _md5sum = "8ea844040bae943d8f96401ca7a88393"
  _type = "teb_local_planner/AgvTrajectoryMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """teb_local_planner/AgvLineMsg[] agv_trajectory
int32 move_dir

================================================================================
MSG: teb_local_planner/AgvLineMsg
# The pose of the robot
geometry_msgs/Pose[3] poses

std_msgs/Int32 type

std_msgs/Int32 path_id

float64 vel

int32 crossing

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: std_msgs/Int32
int32 data"""
  __slots__ = ['agv_trajectory','move_dir']
  _slot_types = ['teb_local_planner/AgvLineMsg[]','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       agv_trajectory,move_dir

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AgvTrajectoryMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.agv_trajectory is None:
        self.agv_trajectory = []
      if self.move_dir is None:
        self.move_dir = 0
    else:
      self.agv_trajectory = []
      self.move_dir = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.agv_trajectory)
      buff.write(_struct_I.pack(length))
      for val1 in self.agv_trajectory:
        for val2 in val1.poses:
          _v1 = val2.position
          _x = _v1
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v2 = val2.orientation
          _x = _v2
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
        _v3 = val1.type
        buff.write(_get_struct_i().pack(_v3.data))
        _v4 = val1.path_id
        buff.write(_get_struct_i().pack(_v4.data))
        _x = val1
        buff.write(_get_struct_di().pack(_x.vel, _x.crossing))
      buff.write(_get_struct_i().pack(self.move_dir))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.agv_trajectory is None:
        self.agv_trajectory = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.agv_trajectory = []
      for i in range(0, length):
        val1 = teb_local_planner.msg.AgvLineMsg()
        val1.poses = []
        for i in range(0, 3):
          val2 = geometry_msgs.msg.Pose()
          _v5 = val2.position
          _x = _v5
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v6 = val2.orientation
          _x = _v6
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          val1.poses.append(val2)
        _v7 = val1.type
        start = end
        end += 4
        (_v7.data,) = _get_struct_i().unpack(str[start:end])
        _v8 = val1.path_id
        start = end
        end += 4
        (_v8.data,) = _get_struct_i().unpack(str[start:end])
        _x = val1
        start = end
        end += 12
        (_x.vel, _x.crossing,) = _get_struct_di().unpack(str[start:end])
        self.agv_trajectory.append(val1)
      start = end
      end += 4
      (self.move_dir,) = _get_struct_i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.agv_trajectory)
      buff.write(_struct_I.pack(length))
      for val1 in self.agv_trajectory:
        for val2 in val1.poses:
          _v9 = val2.position
          _x = _v9
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v10 = val2.orientation
          _x = _v10
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
        _v11 = val1.type
        buff.write(_get_struct_i().pack(_v11.data))
        _v12 = val1.path_id
        buff.write(_get_struct_i().pack(_v12.data))
        _x = val1
        buff.write(_get_struct_di().pack(_x.vel, _x.crossing))
      buff.write(_get_struct_i().pack(self.move_dir))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.agv_trajectory is None:
        self.agv_trajectory = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.agv_trajectory = []
      for i in range(0, length):
        val1 = teb_local_planner.msg.AgvLineMsg()
        val1.poses = []
        for i in range(0, 3):
          val2 = geometry_msgs.msg.Pose()
          _v13 = val2.position
          _x = _v13
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v14 = val2.orientation
          _x = _v14
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          val1.poses.append(val2)
        _v15 = val1.type
        start = end
        end += 4
        (_v15.data,) = _get_struct_i().unpack(str[start:end])
        _v16 = val1.path_id
        start = end
        end += 4
        (_v16.data,) = _get_struct_i().unpack(str[start:end])
        _x = val1
        start = end
        end += 12
        (_x.vel, _x.crossing,) = _get_struct_di().unpack(str[start:end])
        self.agv_trajectory.append(val1)
      start = end
      end += 4
      (self.move_dir,) = _get_struct_i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_di = None
def _get_struct_di():
    global _struct_di
    if _struct_di is None:
        _struct_di = struct.Struct("<di")
    return _struct_di
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
