FpLocalPlannerROS:

 odom_topic: odom
    
 # Trajectory
  
 teb_autosize: True
 dt_ref: 0.3
 dt_hysteresis: 0.1
 global_plan_overwrite_orientation: True
 allow_init_with_backwards_motion: False
 max_global_plan_lookahead_dist: 2.0
 feasibility_check_no_poses: 15
 feasibility_check_dist: 1.0
 oscillation_filter_duration: 2.0
 oscillation_recovery_min_duration: 10.0
 global_plan_viapoint_sep: -1.0
 exact_arc_length: True
 pid_scales: 1.0
 line_scales: 3.0
 dist_kp: 1.5
 dist_ki: 0.0
 dist_kd: 0.0
 angle_kp: 1.0
 angle_ki: 0.0
 angle_kd: 0.0
 dist_angle_scales: 0.7
 # Robot
 v_scales: 0.2
 angle_add_scales: 0.03
 max_vel_x_backwards: 0.01

 agv_max_ang_diff: 0.5
 agv_max_dist_line: 0.5
 reach_togoal_dist: 0.3
 agv_rotate_enable: False
 fp_max_calSize: 10
 min_turning_radius: 0.0
 cmd_angle_instead_rotvel: False

 footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
   type: "point"
   radius: 0.2 # for type "circular"
   line_start: [0.0, 0.0] # for type "line"
   line_end: [1.375, 0.0] # for type "line"mark
   front_offset: 0.2 # for type "two_circles"
   front_radius: 0.2 # for type "two_circles"
   rear_offset: 0.2 # for type "two_circles"
   rear_radius: 0.2 # for type "two_circles"
   vertices: [ [0.25, -0.05], [0.18, -0.05], [0.18, -0.18], [-0.19, -0.18], [-0.25, 0], [-0.19, 0.18], [0.18, 0.18], [0.18, 0.05], [0.25, 0.05] ] # for type "polygon"

 # Optimization
    
 no_inner_iterations: 5
 no_outer_iterations: 4
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.1
 weight_max_vel_x: 1
 weight_max_vel_theta: 1
 weight_acc_lim_x: 1
 weight_acc_lim_theta: 1
 weight_kinematics_nh: 10000
 weight_kinematics_forward_drive: 10000
 weight_kinematics_turning_radius: 1
 weight_optimaltime: 1.0
 weight_obstacle: 0
 weight_viapoint: 0
 weight_dynamic_obstacle: 0 # not in use yet
 weight_adapt_factor: 0
 weight_prefer_rotdir: 1.0
 weight_desire_traj: 1.0
 # Homotopy Class Planner
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
