TebLocalPlannerROS:

 odom_topic: odom
    
 # Trajectory
  
 teb_autosize: True
 dt_ref: 0.2
 dt_hysteresis: 0.02
 global_plan_overwrite_orientation: True
 allow_init_with_backwards_motion: False
 max_global_plan_lookahead_dist: 2.0
 feasibility_check_no_poses: 10
 oscillation_filter_duration: 2.0
 oscillation_recovery_min_duration: 10.0
 weight_prefer_rotdir: 2
 # Robot
 max_vel_x_backwards: 0.01
 min_turning_radius: 0.0 # diff-drive robot (can turn on place!)
 shrink_horizon_min_duration: 3.0
 footprint_model:
   type: "point"

 # Obstacles

 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.5
 obstacle_poses_affected: 30
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 2

 # Optimization
    
 no_inner_iterations: 5
 no_outer_iterations: 4
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.1
 obstacle_penalty_epsilon: 0.1
 weight_max_vel_x: 2
 weight_max_vel_theta: 1
 weight_acc_lim_x: 1
 weight_acc_lim_theta: 1
 weight_kinematics_nh: 1200
 weight_kinematics_forward_drive: 10000
 weight_kinematics_turning_radius: 1
 weight_optimaltime: 5.0
 weight_obstacle: 50
 weight_dynamic_obstacle: 10 # not in use yet
 weight_adapt_factor: 2

 # Homotopy Class Planner

 enable_homotopy_class_planning: True
 enable_multithreading: False
 simple_exploration: False
 max_number_classes: 1
 selection_cost_hysteresis: 1.0
 selection_obst_cost_scale: 1.0
 selection_alternative_time_cost: False
 
 roadmap_graph_no_samples: 10
 roadmap_graph_area_width: 4
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False
