(cl:defpackage custom_sys_msgs-srv
  (:use )
  (:export
   "AGV_GRAPH"
   "<AGV_GRAPH-REQUEST>"
   "AGV_GRAPH-REQUEST"
   "<AGV_GRAPH-RESPONSE>"
   "AGV_GRAPH-RESPONSE"
   "BOOCAX_VERSION"
   "<BOOCAX_VERSION-REQUEST>"
   "BOOCAX_VERSION-REQUEST"
   "<BOOCAX_VERSION-RESPONSE>"
   "BOOCAX_VERSION-RESPONSE"
   "READ_RFID"
   "<READ_RFID-REQUEST>"
   "READ_RFID-REQUEST"
   "<READ_RFID-RESPONSE>"
   "READ_RFID-RESPONSE"
  ))

