# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from custom_sys_msgs/AgvNodeMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class AgvNodeMsg(genpy.Message):
  _md5sum = "425f24322817c1acfbde4fee56a7fac2"
  _type = "custom_sys_msgs/AgvNodeMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 node_id
string node_name
int32 node_type
int32 ref_cnt
geometry_msgs/Pose pos

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['node_id','node_name','node_type','ref_cnt','pos']
  _slot_types = ['int32','string','int32','int32','geometry_msgs/Pose']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       node_id,node_name,node_type,ref_cnt,pos

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AgvNodeMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.node_id is None:
        self.node_id = 0
      if self.node_name is None:
        self.node_name = ''
      if self.node_type is None:
        self.node_type = 0
      if self.ref_cnt is None:
        self.ref_cnt = 0
      if self.pos is None:
        self.pos = geometry_msgs.msg.Pose()
    else:
      self.node_id = 0
      self.node_name = ''
      self.node_type = 0
      self.ref_cnt = 0
      self.pos = geometry_msgs.msg.Pose()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_i().pack(self.node_id))
      _x = self.node_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2i7d().pack(_x.node_type, _x.ref_cnt, _x.pos.position.x, _x.pos.position.y, _x.pos.position.z, _x.pos.orientation.x, _x.pos.orientation.y, _x.pos.orientation.z, _x.pos.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.pos is None:
        self.pos = geometry_msgs.msg.Pose()
      end = 0
      start = end
      end += 4
      (self.node_id,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.node_name = str[start:end].decode('utf-8')
      else:
        self.node_name = str[start:end]
      _x = self
      start = end
      end += 64
      (_x.node_type, _x.ref_cnt, _x.pos.position.x, _x.pos.position.y, _x.pos.position.z, _x.pos.orientation.x, _x.pos.orientation.y, _x.pos.orientation.z, _x.pos.orientation.w,) = _get_struct_2i7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_get_struct_i().pack(self.node_id))
      _x = self.node_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2i7d().pack(_x.node_type, _x.ref_cnt, _x.pos.position.x, _x.pos.position.y, _x.pos.position.z, _x.pos.orientation.x, _x.pos.orientation.y, _x.pos.orientation.z, _x.pos.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.pos is None:
        self.pos = geometry_msgs.msg.Pose()
      end = 0
      start = end
      end += 4
      (self.node_id,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.node_name = str[start:end].decode('utf-8')
      else:
        self.node_name = str[start:end]
      _x = self
      start = end
      end += 64
      (_x.node_type, _x.ref_cnt, _x.pos.position.x, _x.pos.position.y, _x.pos.position.z, _x.pos.orientation.x, _x.pos.orientation.y, _x.pos.orientation.z, _x.pos.orientation.w,) = _get_struct_2i7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
_struct_2i7d = None
def _get_struct_2i7d():
    global _struct_2i7d
    if _struct_2i7d is None:
        _struct_2i7d = struct.Struct("<2i7d")
    return _struct_2i7d
