# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from custom_sys_msgs/GripTaskMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GripTaskMsg(genpy.Message):
  _md5sum = "edcdb33fee8dd1cca389a115bb5f85d4"
  _type = "custom_sys_msgs/GripTaskMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int8 src_dir
float32 src_height
int8 dst_dir
float32 dst_height
int8 final_homing
"""
  __slots__ = ['src_dir','src_height','dst_dir','dst_height','final_homing']
  _slot_types = ['int8','float32','int8','float32','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       src_dir,src_height,dst_dir,dst_height,final_homing

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GripTaskMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.src_dir is None:
        self.src_dir = 0
      if self.src_height is None:
        self.src_height = 0.
      if self.dst_dir is None:
        self.dst_dir = 0
      if self.dst_height is None:
        self.dst_height = 0.
      if self.final_homing is None:
        self.final_homing = 0
    else:
      self.src_dir = 0
      self.src_height = 0.
      self.dst_dir = 0
      self.dst_height = 0.
      self.final_homing = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_bfbfb().pack(_x.src_dir, _x.src_height, _x.dst_dir, _x.dst_height, _x.final_homing))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 11
      (_x.src_dir, _x.src_height, _x.dst_dir, _x.dst_height, _x.final_homing,) = _get_struct_bfbfb().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_bfbfb().pack(_x.src_dir, _x.src_height, _x.dst_dir, _x.dst_height, _x.final_homing))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 11
      (_x.src_dir, _x.src_height, _x.dst_dir, _x.dst_height, _x.final_homing,) = _get_struct_bfbfb().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_bfbfb = None
def _get_struct_bfbfb():
    global _struct_bfbfb
    if _struct_bfbfb is None:
        _struct_bfbfb = struct.Struct("<bfbfb")
    return _struct_bfbfb
