# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from custom_sys_msgs/PositionVerificationInfo.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PositionVerificationInfo(genpy.Message):
  _md5sum = "7ce66b05d8b3d1f15000aa53d885fc04"
  _type = "custom_sys_msgs/PositionVerificationInfo"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 loc_status
float64 suggest_max_vx
float64 suggest_max_vtheta
"""
  __slots__ = ['loc_status','suggest_max_vx','suggest_max_vtheta']
  _slot_types = ['int32','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       loc_status,suggest_max_vx,suggest_max_vtheta

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PositionVerificationInfo, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.loc_status is None:
        self.loc_status = 0
      if self.suggest_max_vx is None:
        self.suggest_max_vx = 0.
      if self.suggest_max_vtheta is None:
        self.suggest_max_vtheta = 0.
    else:
      self.loc_status = 0
      self.suggest_max_vx = 0.
      self.suggest_max_vtheta = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i2d().pack(_x.loc_status, _x.suggest_max_vx, _x.suggest_max_vtheta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.loc_status, _x.suggest_max_vx, _x.suggest_max_vtheta,) = _get_struct_i2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i2d().pack(_x.loc_status, _x.suggest_max_vx, _x.suggest_max_vtheta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.loc_status, _x.suggest_max_vx, _x.suggest_max_vtheta,) = _get_struct_i2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i2d = None
def _get_struct_i2d():
    global _struct_i2d
    if _struct_i2d is None:
        _struct_i2d = struct.Struct("<i2d")
    return _struct_i2d
