// Auto-generated. Do not edit!

// (in-package custom_sys_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let AgvTrajectoryMsg2 = require('./AgvTrajectoryMsg2.js');

//-----------------------------------------------------------

class TrackPathGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.path = null;
    }
    else {
      if (initObj.hasOwnProperty('path')) {
        this.path = initObj.path
      }
      else {
        this.path = new AgvTrajectoryMsg2();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type TrackPathGoal
    // Serialize message field [path]
    bufferOffset = AgvTrajectoryMsg2.serialize(obj.path, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type TrackPathGoal
    let len;
    let data = new TrackPathGoal(null);
    // Deserialize message field [path]
    data.path = AgvTrajectoryMsg2.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += AgvTrajectoryMsg2.getMessageSize(object.path);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'custom_sys_msgs/TrackPathGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '41dbbfcb0dbb3f1d634a3fc79ec5237d';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # goal: a path to exe
    custom_sys_msgs/AgvTrajectoryMsg2 path
    
    ================================================================================
    MSG: custom_sys_msgs/AgvTrajectoryMsg2
    int32 task_id
    int32 task_type
    int32 vehicle_id
    int32 free_nav
    float64 deadline
    geometry_msgs/Pose dst_pose
    custom_sys_msgs/AgvLineMsg2[] agv_trajectory
    int32 test
    ================================================================================
    MSG: geometry_msgs/Pose
    # A representation of pose in free space, composed of position and orientation. 
    Point position
    Quaternion orientation
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    ================================================================================
    MSG: custom_sys_msgs/AgvLineMsg2
    int32 segment_id
    int32 segment_type
    int32 attitude
    int32 tracking_mode
    float64 speed
    float64 precision
    float64 arrival_time
    float64 departure_time
    float64 redundancy_time
    geometry_msgs/Pose p_start
    geometry_msgs/Pose p_middle
    geometry_msgs/Pose p_end
    int32 start_node_id
    int32 end_node_id
    bool crossing
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new TrackPathGoal(null);
    if (msg.path !== undefined) {
      resolved.path = AgvTrajectoryMsg2.Resolve(msg.path)
    }
    else {
      resolved.path = new AgvTrajectoryMsg2()
    }

    return resolved;
    }
};

module.exports = TrackPathGoal;
