(cl:in-package custom_sys_msgs-msg)
(cl:export '(SEGMENT_ID-VAL
          SEGMENT_ID
          SEGMENT_TYPE-VAL
          SEGMENT_TYPE
          ATTITUDE-VAL
          ATTITUDE
          TRACKING_MODE-VAL
          TRACKING_MODE
          SPEED-VAL
          SPEED
          PRECISION-VAL
          PRECISION
          ARRIVAL_TIME-VAL
          ARRIVAL_TIME
          DEPARTURE_TIME-VAL
          DEPARTURE_TIME
          REDUNDANCY_TIME-VAL
          REDUNDANCY_TIME
          P_START-VAL
          P_START
          P_MIDDLE-VAL
          P_MIDDLE
          P_END-VAL
          P_END
          START_NODE_ID-VAL
          START_NODE_ID
          END_NODE_ID-VAL
          END_NODE_ID
          CROSSING-VAL
          CROSSING
))