(cl:in-package custom_sys_msgs-msg)
(cl:export '(TASK_ID-VAL
          TASK_ID
          TASK_MILE-VAL
          TASK_MILE
          TASK_PROGRESSS-VAL
          TASK_PROGRESSS
          STATUS_CODE-VAL
          STATUS_CODE
          SUB_CODE-VAL
          SUB_CODE
          SEGMENT_ID-VAL
          SEGMENT_ID
          DIR-VAL
          DIR
          SEGMENT_MILE-VAL
          SEGMENT_MILE
          NODE_ID-VAL
          NODE_ID
          DST_NODE-VAL
          DST_NODE
          POSE-VAL
          POSE
          VELL-VAL
          VELL
          NODE_REQUEST-VAL
          NODE_REQUEST
          NODE_OCCUPY-VAL
          NODE_OCCUPY
          NODE_RELEASE-VAL
          NODE_RELEASE
          WORK_MODE-VAL
          WORK_MODE
          LOCATION_STATUS-VAL
          LOCATION_STATUS
          ATTITUDE-VAL
          ATTITUDE
          CHECK_TIME-VAL
          CHECK_TIME
))