; Auto-generated. Do not edit!


(cl:in-package custom_sys_msgs-msg)


;//! \htmlinclude TrackTargetGoal.msg.html

(cl:defclass <TrackTargetGoal> (roslisp-msg-protocol:ros-message)
  ((path
    :reader path
    :initarg :path
    :type custom_sys_msgs-msg:AgvTrajectoryMsg2
    :initform (cl:make-instance 'custom_sys_msgs-msg:AgvTrajectoryMsg2)))
)

(cl:defclass TrackTargetGoal (<TrackTargetGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TrackTargetGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TrackTargetGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name custom_sys_msgs-msg:<TrackTargetGoal> is deprecated: use custom_sys_msgs-msg:TrackTargetGoal instead.")))

(cl:ensure-generic-function 'path-val :lambda-list '(m))
(cl:defmethod path-val ((m <TrackTargetGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader custom_sys_msgs-msg:path-val is deprecated.  Use custom_sys_msgs-msg:path instead.")
  (path m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TrackTargetGoal>) ostream)
  "Serializes a message object of type '<TrackTargetGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'path) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TrackTargetGoal>) istream)
  "Deserializes a message object of type '<TrackTargetGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'path) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TrackTargetGoal>)))
  "Returns string type for a message object of type '<TrackTargetGoal>"
  "custom_sys_msgs/TrackTargetGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TrackTargetGoal)))
  "Returns string type for a message object of type 'TrackTargetGoal"
  "custom_sys_msgs/TrackTargetGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TrackTargetGoal>)))
  "Returns md5sum for a message object of type '<TrackTargetGoal>"
  "41dbbfcb0dbb3f1d634a3fc79ec5237d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TrackTargetGoal)))
  "Returns md5sum for a message object of type 'TrackTargetGoal"
  "41dbbfcb0dbb3f1d634a3fc79ec5237d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TrackTargetGoal>)))
  "Returns full string definition for message of type '<TrackTargetGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal: a aoa tag to follow~%custom_sys_msgs/AgvTrajectoryMsg2 path~%~%================================================================================~%MSG: custom_sys_msgs/AgvTrajectoryMsg2~%int32 task_id~%int32 task_type~%int32 vehicle_id~%int32 free_nav~%float64 deadline~%geometry_msgs/Pose dst_pose~%custom_sys_msgs/AgvLineMsg2[] agv_trajectory~%int32 test~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%================================================================================~%MSG: custom_sys_msgs/AgvLineMsg2~%int32 segment_id~%int32 segment_type~%int32 attitude~%int32 tracking_mode~%float64 speed~%float64 precision~%float64 arrival_time~%float64 departure_time~%float64 redundancy_time~%geometry_msgs/Pose p_start~%geometry_msgs/Pose p_middle~%geometry_msgs/Pose p_end~%int32 start_node_id~%int32 end_node_id~%bool crossing~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TrackTargetGoal)))
  "Returns full string definition for message of type 'TrackTargetGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal: a aoa tag to follow~%custom_sys_msgs/AgvTrajectoryMsg2 path~%~%================================================================================~%MSG: custom_sys_msgs/AgvTrajectoryMsg2~%int32 task_id~%int32 task_type~%int32 vehicle_id~%int32 free_nav~%float64 deadline~%geometry_msgs/Pose dst_pose~%custom_sys_msgs/AgvLineMsg2[] agv_trajectory~%int32 test~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%================================================================================~%MSG: custom_sys_msgs/AgvLineMsg2~%int32 segment_id~%int32 segment_type~%int32 attitude~%int32 tracking_mode~%float64 speed~%float64 precision~%float64 arrival_time~%float64 departure_time~%float64 redundancy_time~%geometry_msgs/Pose p_start~%geometry_msgs/Pose p_middle~%geometry_msgs/Pose p_end~%int32 start_node_id~%int32 end_node_id~%bool crossing~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TrackTargetGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'path))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TrackTargetGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'TrackTargetGoal
    (cl:cons ':path (path msg))
))
